{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 4",
      "fix_state": "Will not fix",
      "package_name": "mod_python",
      "cpe": "cpe:/o:redhat:enterprise_linux:4"
    },
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Not affected",
      "package_name": "mod_python",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2004-04-16T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2004-2680 mod_python arbitrary data disclosure flaw",
    "id": "231065",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=231065"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "The Red Hat Security Response Team has rated this issue as having low security impact. We no longer plan to fix this flaw in Red Hat Enterprise Linux 4.",
  "acknowledgement": "",
  "name": "CVE-2004-2680",
  "document_distribution": "",
  "details": [
    "mod_python (libapache2-mod-python) 3.1.4 and earlier does not properly handle when output filters process more than 16384 bytes, which can cause filter.read to return portions of previously freed memory."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2004-2680\nhttps://nvd.nist.gov/vuln/detail/CVE-2004-2680"
  ]
}