{
  "Class": "vulnerability",
  "ID": "oval:com.redhat.cve:def:202014343",
  "Version": "636",
  "Metadata": {
    "Title": "CVE-2020-14343 PyYAML: incomplete fix for CVE-2020-1747 (moderate)",
    "References": [
      {
        "Source": "CVE",
        "RefID": "CVE-2020-14343",
        "RefURL": "https://access.redhat.com/security/cve/CVE-2020-14343"
      }
    ],
    "Description": "DOCUMENTATION: A vulnerability was discovered in the PyYAML library, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747. \n            STATEMENT: Ansible Tower 3.7 uses affected version of PyYAML 3.12 from RHEL, but the use of load() is specified with a SafeLoader when it is called. So Ansible Tower and Ansible Engine are not affected.\n\nRed Hat Quay, from version 3.4 uses the safe_load function which is not affected by this issue. See [1].\n\nEven though the CVSSv3 for this flaw is 9.8, the Impact has been set to Moderate because PyYAML provides a specific method to deal with untrusted input, which is `yaml.safe_load`. `yaml.safe_load` or the SafeLoader loader should be used whenever the input YAML can be modified by a malicious user.\n\n[1] https://github.com/quay/quay/pull/603\n            MITIGATION: Use `yaml.safe_load` or the SafeLoader loader when you parse untrusted input.",
    "Advisory": {
      "From": "secalert@redhat.com",
      "Severity": "Moderate",
      "Issued": {},
      "Updated": {
        "Date": "2021-12-14"
      },
      "Cves": [
        {
          "CveID": "CVE-2020-14343",
          "Cvss3": "9.8/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
          "Cwe": "CWE-20",
          "Impact": "moderate",
          "Href": "https://access.redhat.com/security/cve/CVE-2020-14343",
          "Public": "20200722"
        }
      ],
      "AffectedCpeList": [
        "cpe:/a:redhat:enterprise_linux:9",
        "cpe:/a:redhat:enterprise_linux:9::appstream",
        "cpe:/a:redhat:enterprise_linux:9::crb",
        "cpe:/a:redhat:enterprise_linux:9::highavailability",
        "cpe:/a:redhat:enterprise_linux:9::nfv",
        "cpe:/a:redhat:enterprise_linux:9::realtime",
        "cpe:/a:redhat:enterprise_linux:9::resilientstorage",
        "cpe:/a:redhat:enterprise_linux:9::sap",
        "cpe:/a:redhat:enterprise_linux:9::sap_hana",
        "cpe:/a:redhat:enterprise_linux:9::supplementary",
        "cpe:/o:redhat:enterprise_linux:9",
        "cpe:/o:redhat:enterprise_linux:9::baseos"
      ],
      "Affected": {
        "Resolution": {
          "State": "Will not fix"
        }
      }
    }
  },
  "Criteria": {
    "Operator": "OR",
    "Criterions": [
      {
        "Comment": "Red Hat Enterprise Linux must be installed",
        "TestRef": "oval:com.redhat.cve:tst:20052541004"
      }
    ],
    "Criterias": [
      {
        "Operator": "AND",
        "Criterions": [
          {
            "Comment": "Red Hat Enterprise Linux 9 is installed",
            "TestRef": "oval:com.redhat.cve:tst:20052541003"
          },
          {
            "Comment": "python3-pyyaml is installed",
            "TestRef": "oval:com.redhat.cve:tst:202014343001"
          },
          {
            "Comment": "python3-pyyaml is signed with Red Hat redhatrelease2 key",
            "TestRef": "oval:com.redhat.cve:tst:202014343002"
          }
        ]
      }
    ]
  }
}