{
  "affected_release": [
    {
      "product_name": "Red Hat Enterprise Linux 3",
      "release_date": "2004-02-26T00:00:00Z",
      "advisory": "RHSA-2004:058",
      "package": "mod_python-0:3.0.3-3.ent",
      "cpe": "cpe:/o:redhat:enterprise_linux:3"
    },
    {
      "product_name": "Red Hat Linux 9",
      "release_date": "2004-02-26T00:00:00Z",
      "advisory": "RHSA-2004:063",
      "package": "mod_python",
      "cpe": "cpe:/o:redhat:linux:9"
    }
  ],
  "package_state": null,
  "threat_severity": "Low",
  "public_date": "2003-11-28T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2003-0973 security flaw",
    "id": "1617112",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1617112"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "",
  "acknowledgement": "",
  "name": "CVE-2003-0973",
  "document_distribution": "",
  "details": [
    "Unknown vulnerability in mod_python 3.0.x before 3.0.4, and 2.7.x before 2.7.9, allows remote attackers to cause a denial of service (httpd crash) via a certain query string."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2003-0973\nhttps://nvd.nist.gov/vuln/detail/CVE-2003-0973"
  ]
}