{
  "affected_release": [
    {
      "product_name": "OpenStack Folsom for RHEL 6",
      "release_date": "2013-03-05T00:00:00Z",
      "advisory": "RHSA-2013:0596",
      "package": "openstack-keystone-0:2012.2.3-3.el6ost",
      "cpe": "cpe:/a:redhat:openstack:2::el6"
    },
    {
      "product_name": "OpenStack Folsom for RHEL 6",
      "release_date": "2013-03-21T00:00:00Z",
      "advisory": "RHSA-2013:0657",
      "package": "openstack-nova-0:2012.2.3-4.el6ost",
      "cpe": "cpe:/a:redhat:openstack:2::el6"
    },
    {
      "product_name": "OpenStack Folsom for RHEL 6",
      "release_date": "2013-03-21T00:00:00Z",
      "advisory": "RHSA-2013:0658",
      "package": "openstack-cinder-0:2012.2.3-4.el6ost",
      "cpe": "cpe:/a:redhat:openstack:2::el6"
    },
    {
      "product_name": "OpenStack Folsom for RHEL 6",
      "release_date": "2013-03-21T00:00:00Z",
      "advisory": "RHSA-2013:0670",
      "package": "Django14-0:1.4.4-1.el6ost",
      "cpe": "cpe:/a:redhat:openstack:2::el6"
    }
  ],
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 5",
      "fix_state": "Will not fix",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:5"
    },
    {
      "product_name": "Red Hat Enterprise Linux 6",
      "fix_state": "Will not fix",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:6"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Will not fix",
      "package_name": "python",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat OpenStack Platform 2.1",
      "fix_state": "Affected",
      "package_name": "Django14",
      "cpe": "cpe:/a:redhat:openstack:2.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 2.1",
      "fix_state": "Affected",
      "package_name": "openstack-cinder",
      "cpe": "cpe:/a:redhat:openstack:2.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 2.1",
      "fix_state": "Affected",
      "package_name": "openstack-keystone",
      "cpe": "cpe:/a:redhat:openstack:2.1"
    },
    {
      "product_name": "Red Hat OpenStack Platform 2.1",
      "fix_state": "Affected",
      "package_name": "openstack-nova",
      "cpe": "cpe:/a:redhat:openstack:2.1"
    },
    {
      "product_name": "RHOS Essex Release",
      "fix_state": "Affected",
      "package_name": "Django14",
      "cpe": "cpe:/a:redhat:openstack:1"
    },
    {
      "product_name": "RHOS Essex Release",
      "fix_state": "Affected",
      "package_name": "openstack-keystone",
      "cpe": "cpe:/a:redhat:openstack:1"
    },
    {
      "product_name": "RHOS Essex Release",
      "fix_state": "Affected",
      "package_name": "openstack-nova",
      "cpe": "cpe:/a:redhat:openstack:1"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2013-02-19T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2013-1664 Python xml bindings: Internal entity expansion in Python XML libraries inflicts DoS vulnerabilities",
    "id": "913808",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=913808"
  },
  "cvss": {
    "cvss_base_score": "4.3",
    "cvss_scoring_vector": "AV:N/AC:M/Au:N/C:N/I:N/A:P",
    "status": "verified"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "",
  "statement": "This issue affects the versions of python as shipped with Red Hat Enterprise Linux 5, 6 and 7. Red Hat Product Security has rated this issue as having Moderate security impact. This issue is not currently planned to be addressed in future updates.",
  "acknowledgement": "",
  "name": "CVE-2013-1664",
  "document_distribution": "",
  "details": [
    "The XML libraries for Python 3.4, 3.3, 3.2, 3.1, 2.7, and 2.6, as used in OpenStack Keystone Essex, Folsom, and Grizzly; Compute (Nova) Essex and Folsom; Cinder Folsom; Django; and possibly other products allow remote attackers to cause a denial of service (resource consumption and crash) via an XML Entity Expansion (XEE) attack."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2013-1664\nhttps://nvd.nist.gov/vuln/detail/CVE-2013-1664"
  ]
}