{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "OpenShift Enterprise 1",
      "fix_state": "Under investigation",
      "package_name": "python-virtualenv",
      "cpe": "cpe:/a:redhat:openshift:1"
    },
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Under investigation",
      "package_name": "python-virtualenv",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat OpenShift Enterprise 2",
      "fix_state": "Under investigation",
      "package_name": "python27-python-pip",
      "cpe": "cpe:/a:redhat:openshift:2"
    },
    {
      "product_name": "Red Hat OpenShift Enterprise 2",
      "fix_state": "Under investigation",
      "package_name": "python-virtualenv",
      "cpe": "cpe:/a:redhat:openshift:2"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux",
      "fix_state": "Under investigation",
      "package_name": "python27-python-virtualenv",
      "cpe": "cpe:/a:redhat:rhel_software_collections:1"
    },
    {
      "product_name": "Red Hat Software Collections for Red Hat Enterprise Linux",
      "fix_state": "Under investigation",
      "package_name": "python33-python-virtualenv",
      "cpe": "cpe:/a:redhat:rhel_software_collections:1"
    }
  ],
  "threat_severity": "Low",
  "public_date": "2013-10-09T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2014-8991 python-pip: local DoS vulnerability",
    "id": "1166137",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1166137"
  },
  "cvss": {
    "cvss_base_score": "2.1",
    "cvss_scoring_vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
    "status": "draft"
  },
  "cvss3": {
    "cvss3_base_score": "",
    "cvss3_scoring_vector": "",
    "status": ""
  },
  "iava": "",
  "cwe": "CWE-377",
  "statement": "Red Hat Product Security has rated this issue as having Low security impact. This issue is not currently planned to be addressed in future updates. For additional information, refer to the Issue Severity Classification: https://access.redhat.com/security/updates/classification/.",
  "acknowledgement": "",
  "name": "CVE-2014-8991",
  "document_distribution": "",
  "details": [
    "pip 1.3 through 1.5.6 allows local users to cause a denial of service (prevention of package installation) by creating a /tmp/pip-build-* file for another user."
  ],
  "references": [
    "https://www.cve.org/CVERecord?id=CVE-2014-8991\nhttps://nvd.nist.gov/vuln/detail/CVE-2014-8991"
  ]
}